PhotoGallery/Controllers/PhotoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PhotoGallery.Context;
using PhotoGallery.Models;
using PhotoGallery.Services;
using System.Security.Claims;

namespace PhotoGallery.Controllers
{
    [Authorize]
    public class PhotoController : Controller
    {
        private readonly IPhotoService _photoService;

        public PhotoController(IPhotoService service)
        {
            _photoService = service;
        }

        // GET: PhotoController
        public ActionResult Index()
        {
            var lstPhotos = _photoService.GetPhotos();
            return View(lstPhotos);
        }

        // GET: PhotoController/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                var photoModel = _photoService.GetPhoto(id);
                return View(photoModel);
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        // GET: PhotoController/Create
        public ActionResult Create()
        {
            List<CategoryModel> categories = new List<CategoryModel>();
            categories.Add(new CategoryModel
            {
                Id = 0,
                Title = "Please select category",
            });
            var lstCategory = _photoService.GetCategories();
            categories.AddRange(lstCategory);

            List<LocationModel> locations = new List<LocationModel>();
            locations.Add(new LocationModel
            {
                Id = 0,
                Name = "Please select location",
            });
            var lstLocation = _photoService.GetLocations();
            locations.AddRange(lstLocation);

            ViewBag.CategoryList = categories;
            ViewBag.LocationList = locations;
            return View();
        }

        // POST: PhotoController/Create
        [HttpPost]
        public ActionResult Create(PhotoModel reqModel)
        {
            ResponseModel respModel = new ResponseModel();
            try
            {
                if(reqModel != null)
                {
                    if (HttpContext.User.Identity.IsAuthenticated)
                    {
                        var test = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                        var username = HttpContext.User.FindFirst(ClaimTypes.Name)?.Value;
                        reqModel.Owner = username;
                    }
                    else
                    {
                        reqModel.Owner = "";
                    }

                    respModel = _photoService.Create(reqModel);
                }
                else
                {
                    respModel.RespCode = "999";
                    respModel.RespMessage = "Insert failed!";
                }
            }
            catch (Exception ex)
            {
                respModel.RespCode = "999";
                respModel.RespMessage = "Error: " + ex.Message;
            }

            return Json(respModel);
        }

        // GET: PhotoController/Edit/5
        public ActionResult Edit(int id)
        {
            List<CategoryModel> categories = new List<CategoryModel>();
            var lstCategory = _photoService.GetCategories();
            categories.AddRange(lstCategory);

            List<LocationModel> locations = new List<LocationModel>();
            var lstLocation = _photoService.GetLocations();
            locations.AddRange(lstLocation);

            ViewBag.CategoryList = categories;
            ViewBag.LocationList = locations;
            var photoModel = _photoService.GetPhoto(id);
            return View(photoModel);
        }

        // POST: PhotoController/Edit/5
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id, PhotoModel model)
        {
            ResponseModel respModel = new ResponseModel();
            try
            {
                if (model != null)
                {
                    if (HttpContext.User.Identity.IsAuthenticated)
                    {
                        var username = HttpContext.User.FindFirst(ClaimTypes.Name)?.Value;
                        model.Owner = username;
                    }
                    else
                    {
                        model.Owner = "";
                    }
                    respModel = _photoService.Update(id,model);
                }
                else
                {
                    respModel.RespCode = "999";
                    respModel.RespMessage = "Update failed!";
                }
            }
            catch (Exception ex)
            {
                respModel.RespCode = "999";
                respModel.RespMessage = "Error: " + ex.Message;
            }

            return Json(respModel);
        }

        // POST: PhotoController/Delete/5
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int id)
        {
            ResponseModel respModel = new ResponseModel();
            try
            {
                respModel = await _photoService.Delete(id);
            }
            catch (Exception ex)
            {
                respModel.RespCode = "999";
                respModel.RespMessage = ex.Message + ex.StackTrace;
            }
            return Json(respModel);
        }
    }
}

PhotoGallery/Views/Photo/Create.cshtml
@model PhotoGallery.Models.PhotoModel

@{
    Layout = "_AdminLteLayout";
    ViewData["Title"] = "Create Photo";
}

<style>
    .card-img-top {
        width: 200px;
        height:200px;
    }
</style>

<h1>Upload Photo</h1>
<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="CategoryId">Category</label>
        <select asp-for="CategoryId" asp-items="@(new SelectList(ViewBag.CategoryList, "Id", "Title"))" class="form-control" onchange="checkValidationOnChange();" required></select>
        <span id="categoryError" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="LocationId">Location</label>
        <select asp-for="LocationId" asp-items="@(new SelectList(ViewBag.LocationList, "Id", "Name"))" class="form-control" onchange="checkValidationOnChange()" required></select>
        <span id="locationError" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Title">Title</label>
        <input asp-for="Title" class="form-control" onchange="checkValidationOnChange();" required />
        <span id="titleError" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description">Description</label>
        <textarea asp-for="Description" class="form-control" onchange="checkValidationOnChange();"></textarea>
        <span id="descError" class="text-danger"></span>
    </div>

    <div class="form-group m-2">
        <label asp-for="ImageFile">Upload Image</label>
        <input asp-for="ImageFile" type="file" class="form-control-file" id="ImageFile" onchange="previewImage();" name="ImageFile" required />
        <span id="fileError" class="text-danger"></span>
    </div>

    <div class="form-group">
        @* ~/assets/adnovum.png *@
    <img id="preview" class="card-img-top img-thumbnail" src="" alt="Card image cap">
    <div></div>
    <input type="button" id="uploadButton" value="Upload" class="btn btn-primary" />
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        function previewImage() 
        {
            const fileInput = document.getElementById('ImageFile');
            const preview = document.getElementById('preview');

            if (fileInput.files && fileInput.files[0]) {
                const reader = new FileReader();

                reader.onload = function (e) {
                    preview.src = e.target.result;
                    preview.style.display = "block"; // Show the image element
                }

                reader.readAsDataURL(fileInput.files[0]);
            }
        }

        $("#uploadButton").click(function () 
        {
            checkValidation();

            var formData = new FormData();
            formData.append("CategoryId", $('#CategoryId').val());
            formData.append("LocationId", $('#LocationId').val());
            formData.append("Title", $('#Title').val());
            formData.append("Description", $('#Description').val());
            var photoFile = $('#ImageFile')[0].files[0];
            console.log(photoFile);
            if (photoFile && photoFile.size > 0) 
            {
                formData.append("ImageFile", photoFile);
            } 
            else 
            {
                formData.append("ImageFile", "");
            }

            $.ajax({
                url: "/Photo/Create",
                type: "POST",
                data: formData,
                processData: false,
                contentType: false,
                success: function (data) {
                    console.log(data);
                    if (data.respCode == "000") {
                        SuccessMessageBoxWithLink('Photo Create is Successful', '/Photo/Index');
                    } else if (data.respCode == "999") {
                        ErrorMessageBox('Photo Create is Fail');
                    }
                },
                error: function (xhr, status, error) {
                    console.log(xhr.responseText); // Log the detailed error message for debugging
                }
            });
        });

        function checkValidation() {
            var selectedCategoryId = $('#CategoryId').val();
            if (selectedCategoryId == "0") 
            {
                document.getElementById("categoryError").textContent = "Please select a category";
                e.preventDefault();
            }
            var selectedLocationId = $('#LocationId').val();
            if (selectedLocationId == "0") {
                document.getElementById("locationError").textContent = "Please select location";
                e.preventDefault();
            }
            const titleInput = $('#Title').val();
            if (titleInput.length <= 0) {
                document.getElementById("titleError").textContent = "Please enter a title";
                e.preventDefault();
            }
            const descInput = $('#Description').val();
            if (descInput.length <= 0) {
                document.getElementById("descError").textContent = "Please enter a description";
                e.preventDefault();
            }
            const fileInput = document.getElementById("ImageFile");
            if (fileInput.files.length === 0) {
                document.getElementById("fileError").textContent = "Please select a file";
                e.preventDefault();
            }
            else{
                document.getElementById("fileError").textContent = "";
            }
        }

        function checkValidationOnChange() 
        {
            var selectedCategoryId = $('#CategoryId').val();
            if (selectedCategoryId != "0")
            {
                document.getElementById("categoryError").textContent = "";
            }
            var selectedLocationId = $('#LocationId').val();
            if (selectedLocationId != "0")
            {
                document.getElementById("locationError").textContent = "";
            }
            const titleInput = $('#Title').val();
            if (titleInput.length >= 0) 
            {
                document.getElementById("titleError").textContent = "";
            }
            const descInput = $('#Description').val();
            if (descInput.length >= 0) {
                document.getElementById("descError").textContent = "";
            }
        }
    </script>
}

PhotoGallery/Views/Photo/Details.cshtml
@model PhotoGallery.Models.PhotoModel

@{
    Layout = "_AdminLteLayout";
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div class="container">
    <div class="row">
        <div class="col-md-6">
              @if (Model.Image != null && Model.Image.Length > 0)
               {
                  <img class="img-fluid rounded-start" style="height:300px" src="data:image/png;base64,@(Convert.ToBase64String(Model.Image))" />
               }
         </div>
         <div class ="col-md-6">
             <div class="card-body">
                <div>
                    <h5>Caption</h5>
                    <p>@Model.Title</p>
                </div>

                <div>
                    <h5>Uploaded On</h5>
                    <p>@Model.UploadedDate.ToShortDateString()</p>
                </div>

                <div>
                    <h5>Description</h5>
                    <p>@Model.Description</p>
                </div>

                <div>
                    <h5>Location</h5>
                    <p>@Model.Location</p>
                </div>

                <div>
                    <h5>Category</h5>
                    <p>@Model.Category</p>
                </div>
            </div>
         </div>
    </div>
    <div class="m-3">
            <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
            <a class="btn btn-primary" asp-action="Index">Back to List</a>
    </div>
</div>

PhotoGallery/Views/Photo/Edit.cshtml
@model PhotoGallery.Models.PhotoModel

@{
    Layout = "_AdminLteLayout";
    ViewData["Title"] = "Edit";
}

<style>
    .card-img-top {
        width: 200px;
        height: 200px;
    }
</style>
<h1>Edit</h1>

<h4>PhotoModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="CategoryId">Category</label>
                <select asp-for="CategoryId" asp-items="@(new SelectList(ViewBag.CategoryList, "Id", "Title"))" class="form-control" required></select>
            </div>
            <div class="form-group">
                <label asp-for="LocationId">Location</label>
                <select asp-for="LocationId" asp-items="@(new SelectList(ViewBag.LocationList, "Id", "Name"))" class="form-control" required></select>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group m-2">
                <label asp-for="ImageFile">Upload Image</label>
                <input asp-for="ImageFile" type="file" class="form-control-file" id="ImageFile" name="ImageFile" onchange="previewImage();" required />
            </div>
            <img id="preview" class="card-img-top img-thumbnail" src="data:image/png;base64,@Convert.ToBase64String(Model.Image)" alt="Card image cap">
            <div class="form-group">
                <input type="button" id="uploadButton" value="Update" class="btn btn-primary" style="margin-top: 15px;" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        function previewImage() {
            const fileInput = document.getElementById('ImageFile');
            const preview = document.getElementById('preview');

            if (fileInput.files && fileInput.files[0]) {
                const reader = new FileReader();

                reader.onload = function (e) {
                    preview.src = e.target.result;
                    preview.style.display = "block"; // Show the image element
                }

                reader.readAsDataURL(fileInput.files[0]);
            }
        }

        $("#uploadButton").click(function () {
            var Id = $('#Id').val();
            var formData = new FormData();
            formData.append("Id", $('#Id').val());
            formData.append("CategoryId", $('#CategoryId').val());
            formData.append("LocationId", $('#LocationId').val());
            formData.append("Title", $('#Title').val());
            formData.append("Description", $('#Description').val());
            var photoFile = $('#ImageFile')[0].files[0];
            console.log(photoFile);
            if (photoFile && photoFile.size > 0) {
                formData.append("ImageFile", photoFile);
            } else {
                formData.append("ImageFile", "");
            }
            
            $.ajax({
                url: "/Photo/Edit/"+ Id,
                type: "POST",
                data: formData,
                processData: false,
                contentType: false,
                success: function (data) {
                    console.log(data);
                    if (data.respCode == "000") {
                        SuccessMessageBoxWithLink('Photo Update is Successful', '/Photo/Index');
                    } else if (data.respCode == "999") {
                        ErrorMessageBox('Photo Update is Fail');
                    }
                },
                error: function (xhr, status, error) {
                    ErrorMessageBox('You are not authorized to perform this action.');
                }
            });
        });
    </script>
}

PhotoGallery/Views/Photo/Index.cshtml
@model IEnumerable<PhotoGallery.Models.PhotoModel>

@{
    Layout = "_AdminLteLayout";
    ViewData["Title"] = "Index";
}

@{
    if (TempData["errorMessage"] != null)
    {
    <div class="alert alert-danger">
                    @TempData["errorMessage"]
    </div>
    }
}

<h1>Photo Lists</h1>

<p>
    <a asp-action="Create" class="btn btn-sm btn-primary">Upload Photo</a>
</p>

<div id="loader" class="text-center">
    <div class="spinner-border" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>

<style>
    body {
        position: relative;
    }

    .photo-card {
        display: none;
    }
</style>

<div class="bg-light">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-3 p-md-2 photo-card">
                <div class="card img-thumbnail" style="width: auto">
                    <img class="card-img-top img-thumbnail" src="data:image/png;base64,@Convert.ToBase64String(item.Image)" alt="Card image cap" style="height:200px">
                    <div class="card-body">
                        <h5 class="card-title">@item.Title</h5>
                        <p class="card-text">Upload Date: @item.UploadedDate.ToShortDateString() </p>
                        <a href="@Url.Action("Details", "Photo", new { id = item.Id })" class="btn btn-sm btn-primary">View Details</a>
                        <button type="button" class="btn btn-sm btn-danger" onclick="deleteItem(@item.Id)">Delete</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<div id="pagination" style="display: flex; align-items: center; justify-content: space-between;">
    <div style="display: flex; align-items: center;">
        <label for="count-dropdown" style="margin-right: 10px;">Show:</label>
        <select id="count-dropdown" class="form-control" style="width: auto;">
            <option value="3">3</option>
            <option value="6">6</option>
            <option value="9">9</option>
        </select>
    </div>
    <div>
        <button id="prev-btn" class="btn btn-sm btn-primary"><i class="fas fa-chevron-left"></i></button>
        <span id="page-count" class="text-black" style="margin: 0 10px;"></span>
        <button id="next-btn" class="btn btn-sm btn-primary"><i class="fas fa-chevron-right"></i></button>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        var currentPage = 1;
        console.log( "test");
        var itemsPerPage = parseInt($('#count-dropdown').val()); // Get initial value from dropdown
        console.log(itemsPerPage + "length");

        function updatePagination() {
            var totalItems = $('.photo-card').length;
            var totalPages = Math.ceil(totalItems / itemsPerPage);

            $('.photo-card').hide();
            $('.photo-card').slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage).show();

            // Handle buttons enable/disable
            $('#prev-btn').prop('disabled', false);
            $('#next-btn').prop('disabled', false);

            if (currentPage == 1) {
                $('#prev-btn').prop('disabled', true);
            }

            if (currentPage == totalPages) {
                $('#next-btn').prop('disabled', true);
            }

            // Show current page and total pages
            $('#page-count').text('Page ' + currentPage + ' of ' + totalPages);
        }
        // $(document).ready(function () $(window).on("load", function()
        $(document).ready(function () {
            updatePagination();

            $('#prev-btn').click(function () {
                if (!$(this).prop('disabled')) {
                    currentPage--;
                    updatePagination();
                }
            });

            $('#next-btn').click(function () {
                if (!$(this).prop('disabled')) {
                    currentPage++;
                    updatePagination();
                }
            });

            $('#count-dropdown').change(function () {
                itemsPerPage = parseInt($(this).val()); // Update items per page when dropdown changes
                currentPage = 1; // Reset current page
                updatePagination();
            });

            $('#loader').hide(); // Hide loader
        });

        function deleteItem(id) {
            ConfirmMessageBox().then((confirmed) => {
                if (confirmed) {
                    $.ajax({
                        url: '/Photo/Delete',
                        type: 'POST',
                        data: { id: id },
                        success: function (data) {
                            console.log(data);
                            if (data.respCode == "000") {
                                SuccessMessageBoxWithLink('Photo Delete is Successful!', '/Photo/Index', 'Success');
                            } else if (data.respCode == "999") {
                                ErrorMessageBox('Photo Delete is Fail!');
                            } else if (data.respCode == "777") {
                                DeleteMessageWithLink(data.respMsg, '/Access/Login', 'Error');
                            }
                        },
                        error: function (xhr, status, error) {
                            console.log(xhr.responseText);
                            console.log(error + " error log");
                            if (xhr.status == 403 || xhr.status == 401) {
                                ErrorMessageBox('You are not authorized to perform this action.');
                            }
                        },
                    });
                }
            });

        }
    </script>
}